from ujamaa import create_app
from ujamaa_models import db
from ujamaa_models.models import User, Post, University, Program, Course, CourseOutline, Exam, Notes
 
 
# drop all of the existing database tables
db.drop_all(app=create_app())
 
# create the database and the database table
db.create_all(app=create_app())


# insert user data
university1 = University('Moi University')
university2 = University('Jomo Kenyatta University of Science and Technology')
university3 = University('Strathmore University')
university3 = University('Kenyatta University')
university3 = University('University Of Nairobi')

db.session.add(university1)
db.session.add(university2)
db.session.add(university3)
db.session.add(university4)
db.session.add(university5)


program1 = Program('Information Technology')
program2 = Program('Business Management')
program3 = Program('Economics')
db.session.add(program1)
db.session.add(program2)
db.session.add(program3)


course1 = Course('Introduction To Computer Systems', 1, program1.id)
course2 = Course('Introduction To Programming', 1, program1.id)
course3 = Course('Discrete Mathematics', 1, program1.id)
course4 = Course('Probability And Statistics', 1, program1.id)
course5 = Course('Operating Systems', 2, program1.id)
course6 = Course('Computer Architecture', 2, program1.id)
course7 = Course('Computer Networks', 2, program1.id)
course8 = Course('Software Engineering', 2, program1.id)
course9 = Course('Analysis And Design Of Algorithms', 3, program1.id)
course10 = Course('Foundations Of Human Computer Interaction', 3, program1.id)
course11 = Course('Management Information Systems', 3, program1.id)
course12 = Course('Distributed Systems', 3, program1.id)
course13 = Course('Computer Network Security', 4, program1.id)
course14 = Course('Icts And Society', 4, program1.id)
course15 = Course('Ict Project Management', 4, program1.id)
course16 = Course('Computer Graphics', 4, program1.id)

course17 = Course('Communication Skills', 1, program2.id)
course18 = Course('Introduction To Business', 1, program2.id)
course19 = Course('Introduction To Micro-economics', 1 , program2.id)
course20 = Course('Introduction To Macro-economics', 1 , program2.id)
course21 = Course('Introduction To Management Accounting', 2 , program2.id)
course22 = Course('Micro-economic Theory', 2, program2.id)
course23 = Course('Organizational Theory', 2, program2.id)
course24= Course('Introduction To Risk And Insurance', 2, program2.id)
course25 = Course('Organizational Behaviour', 3, program2.id)
course26 = Course('Monetary Theory And Practice', 3, program2.id)
course27= Course('Financial Institutions And Markets', 3, program2.id)
course28 = Course('Business Law I', 3, program2.id)
course29 = Course('Principles Of Auditing', 4, program2.id)
course30= Course('Tax Laws And Practice', 4, program2.id)
course31= Course('Strategic Management', 4, program2.id)
course32 = Course('International Finance', 4, program2.id)

course33 = Course('Communication Skills', 1, program3.id)
course34= Course('Introduction To Microeconomics', 1, program3.id)
course35= Course('Introduction To Macroeconomics', 1, program3.id)
course36 = Course('Economic Statistics I', 1, program3.id)
course37= Course('Introduction To Financial Accounting', 2, program3.id)
course38 = Course('Introduction To Management Accounting', 2, program3.id)
course39= Course('Mathematics For Economists I', 2, program3.id)
course40= Course('Introduction To Real Analysis & Topology', 2, program3.id)
course41 = Course('International Economics', 3, program3.id)
course42 = Course('Economic History', 3, program3.id)
course43 = Course('Development Economics', 3, program3.id)
course44 = Course('Intermediate Microeconomics', 3, program3.id)
course45 = Course('Public Economics', 4, program3.id)
course46 = Course('Environmental Economics', 4, program3.id)
course47= Course('Transport Economics', 4, program3.id)
course48 = Course('Economics Of Industry', 4, program3.id)

db.session.add(course1)
db.session.add(course2)
db.session.add(course3)
db.session.add(course4)
db.session.add(course5)
db.session.add(course6)
db.session.add(course7)
db.session.add(course8)
db.session.add(course9)
db.session.add(course10)
db.session.add(course11)
db.session.add(course12)
db.session.add(course13)
db.session.add(course14)
db.session.add(course15)
db.session.add(course16)
db.session.add(course17)
db.session.add(course18)
db.session.add(course19)
db.session.add(course20)
db.session.add(course21)
db.session.add(course22)
db.session.add(course23)
db.session.add(course24)
db.session.add(course25)
db.session.add(course26)
db.session.add(course27)
db.session.add(course28)
db.session.add(course29)
db.session.add(course30)
db.session.add(course31)
db.session.add(course32)
db.session.add(course33)
db.session.add(course34)
db.session.add(course35)
db.session.add(course36)
db.session.add(course37)
db.session.add(course38)
db.session.add(course39)
db.session.add(course40)
db.session.add(course41)
db.session.add(course42)
db.session.add(course43)
db.session.add(course44)
db.session.add(course45)
db.session.add(course46)
db.session.add(course47)
db.session.add(course48)

db.session.commit()